[package]
name = "doorcam"
version = "0.1.0"
authors = ["TheAlgorythm <mos-news@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
base64 = "0.12.3"
blake2 = "0.9.0"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["serve", "tera_templates", "sqlite_pool", "helmet"]
