[package]
name = "doorcam"
version = "0.1.0"
authors = ["TheAlgorythm <mos-news@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["only_web"]
iot = ["rust_gpiozero"]
only_web = []

[dependencies]
rocket = "0.4.5"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
base64 = "0.12.3"
blake2 = "0.9.0"
passwords = "3.1.3"
mqttc = { version = "0.1.4", optional = true }
rust_gpiozero = { version = "0.2.0", optional = true }

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["serve", "tera_templates", "sqlite_pool", "helmet"]
