[iot]
door_opener_pin = 0
tamper_sensor_pin = 1
door_opening_time = "10s"
bell_debounce_interval = "42s"
# tamper_sensor_debounce_interval = "42s"

[web]
mjpeg_stream_port = 8081

[security]
hash_pepper = "0123456789abcdef0123456789abcdef"
minimal_password_strength_score = 80
encryption_key = "0123456789abcdef0123456789abcdef"
allowed_hash_configs = ["Blake2b", "plain"]
